import { DominioTransaccion } from '../../../../../framework/modelo/generico/DominioTransaccion';

export class DtoComunEmpleadomast extends DominioTransaccion {
    empleado : number;
    tipopago : string;
    tipotrabajador : string;
    tipoplanilla : string;
    raza : string;
    religion : string;
    tipovisa : string;
    visafechainicio : Date;
    visafechaexpiracion : Date;
    serviciomilitardesde : Date;
    serviciomilitarhasta : Date;
    numeroarchivo : string;
    unidadnegocioasignada : string;
    locaciondepago : string;
    responsableempleado : string;
    responsablejefe : string;
    responsablesueldo : string;
    codigousuario : string;
    tipoasistenciasocial : string;
    centroasistenciasocial : string;
    tipocarnetasistenciasocial : string;
    carnetasistenciasocial : string;
    tipopension : string;
    fechainiciopension : Date;
    fechaterminopension : Date;
    codigoafp : string;
    numeroafp : string;
    bancocts : string;
    tipocuentacts : string;
    tipomonedacts : string;
    numerocuentacts : string;
    estadoempleado : string;
    fechaingreso : Date;
    fechaultimaplanilla : Date;
    tipocontrato : string;
    fechainiciocontrato : Date;
    fechafincontrato : Date;
    fechacese : Date;
    razoncese : string;
    motivocese : number;
    contratista : number;
    companiasocio : string;
    centrocostos : string;
    afe : string;
    deptoorganizacion : string;
    departamentooperacional : string;
    tipohorario : number;
    gradosalario : string;
    cargo : string;
    posicion : string;
    nivelacceso : string;
    flagipssvida : string;
    flagacctrabajo : string;
    flagsindicato : string;
    flagcooperativa : string;
    flagretencionjudicial : string;
    flagimpuestorenta : string;
    flagreingresos : string;
    flagcomision : string;
    correointerno : string;
    sueldoactuallocal : number;
    sueldoactualdolar : number;
    sueldoanteriorlocal : number;
    sueldoanteriordolar : number;
    monedapago : string;
    perfil : number;
    foto : string;
    nivelsalario : string;
    fechaliquidacion : Date;
    fechareingreso : Date;
    unidadreplicacion : string;
    codigocargo : number;
    ultimafechapagovacacion : Date;
    ultimousuario : string;
    estado : string;
    locacionasignada : string;
    empleadorelacionado : number;
    departamentoorganizacional : string;
    tarjetadecredito : string;
    sucursal : string;
    ruccentroasistenciasocial : string;
    actividad : string;
    gerencia : number;
    subgerencia : number;
    plantillaconcepto : number;
    ultimafechamodif : Date;
    redondeoacuenta : string;
    flagsmf : string;
    firmadigitalizada : string;
    provincia : string;
    posicionorganigrama : number;
    planta : string;
    flagjefedepartamento : string;
    flagporcentaje : string;
    centroriesgosctr : string;
    tipopensionjubilacion : string;
    flagtrabajadorpensionista : string;
    flagsctrsalud : string;
    flagsctrpension : string;
    flagdiscapacidad : string;
    flagsujetocontrol : string;
    flagsindicalizado : string;
    flagdomiciliado : string;
    flagdeconfianza : string;
    empleadoant : string;
    asignacionfamiliar : string;
    ordenservicio : string;
    fechabajaeps : Date;
    tiporemuneracionrtps : string;
    municipalidadnacimiento : string;
    establecimientortps : string;
    proveedorintermediacion : number;
    niveleducativortps : string;
    flagacctrabajop : string;
    sucursalbanconacion : string;
    grupoocupacional : number;
    cliente : number;
    clienteunidad : number;
    tareonivel : number;
    empleadonivel : number;
    tipopuesto : number;
    estadonivelacion : string;
    flagregimenalternativo : string;
    flagjornadamaxima : string;
    flaghorarionocturno : string;
    flagotrosquinta : string;
    flagquintaexonerada : string;
    situacionespecial : string;
    flagmadreresponsabilidad : string;
    flagcentroformacion : string;
    tipomodalidadformativa : string;
    prestadorservicio : string;
    fechavacaciones : Date;
    formato2 : string;
    aprobadornivelacion : number;
    solicitadornivelacion : number;
    flagasegurapension : string;
    categoriaocupacional : string;
    flagconveniodobletrib : string;
    tipocomisionafp : string;
    fuentefinanciamientocp : string;
    actividadcp : string;
    jeferesponsable : number;
    jefequienreporta : number;
    unidadoperativa : string;
    codigounidad : number;
    tiempoContratoTotal : string;
    division : string; 
    oficina : string;
    unidadtrabajo : string;
    ordenOrganigrama : string;
    tiempoServicio : string;
    dptoareaoperativa : number;
    flageducacioncompletaiep : string;
    jeferesponsablecompania : string;
 
    motivo : string;
    costcenterdestination : string;
    centrocostosDescri: string;

    seleccionado: string;
	empleadocodigo: string;
	empleadonombre: string;
	empleadosexo: string;
	empleadodocumento: string;
	companianombre: string;
	unidadnegocioasignadanombre: string;
	sucursalnombre: string;
	unidadoperativanombre: string;
	tipoplanillanombre: string;
	codigocargonombre: string;
	posicionorganigramanombre: string;
	tipocontratonombre: string;
	cargonombre: string;
	gradosalarionombre: string;
	afenombre: string;
	tipotrabajadornombre: string;
	tipohorarionombre: string;
	monedapagonombre: string;
	jeferesponsablenombre: string;
	jeferesponsablecompanianombre: string;
	usaempleado: string;

}